spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-PGJNFJ5\SQLSERVER2017;databaseName=AOP
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: s@1234
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
